# Generated by Django 4.0.3 on 2022-06-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='time_published',
        ),
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_note', to='contacts.note'),
        ),
    ]
