# Generated by Django 4.0.3 on 2022-06-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_note_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_note', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
