# Generated by Django 4.0.3 on 2022-06-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_note_note_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
