# Generated by Django 4.0.3 on 2022-06-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_note_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
        migrations.AlterField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='contacts.contact'),
        ),
    ]
