# Generated by Django 4.0.3 on 2022-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_note_name_alter_note_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='delete_button',
            field=models.BooleanField(null=True),
        ),
    ]
